### ISSUE TITLE
getContractRootDir fails due to vscode.window.activeTextEditor being undefined

### ISSUE THREAD

**Issue by dimitar-nikovski** [PraneshASP/vscode-foundry-test-runner#5]
temporary workaround for me was to swap to:

```js
function getContractRootDir() {
  const currentDir = vscode.workspace.rootPath;
  return currentDir;
}
```

Otherwise, great extension and good effort, it works really well.

**Comment by PraneshASP** [comment]
Thanks for the feedback. Will look into this issue later this week. Feel free to open a PR if you already have a fix!
